/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 03 04:06:01 GMT 2024
 */

package org.springframework.cloud.gcp.storage;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.cloud.ReadChannel;
import com.google.cloud.storage.Blob;
import com.google.cloud.storage.Bucket;
import com.google.cloud.storage.Storage;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.springframework.cloud.gcp.storage.GoogleStorageResourceObject;
import org.springframework.core.io.Resource;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GoogleStorageResourceObject_ESTest extends GoogleStorageResourceObject_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "}oa`6y/ O@J7BioYX");
      Resource resource0 = googleStorageResourceObject0.createRelative("cZ|sY");
      assertTrue(googleStorageResourceObject0.isCreateBlobIfNotExists());
      assertEquals("}oa`6y/cZ|sY", resource0.getDescription());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "C9]_sZWR!P*b~G}!");
      googleStorageResourceObject0.getFilename();
      assertTrue(googleStorageResourceObject0.isCreateBlobIfNotExists());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "Gfo?m<+_=R", false);
      boolean boolean0 = googleStorageResourceObject0.exists();
      assertFalse(boolean0);
      assertFalse(googleStorageResourceObject0.isCreateBlobIfNotExists());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "U0o[Y%n/'gcWJ");
      boolean boolean0 = googleStorageResourceObject0.isCreateBlobIfNotExists();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "https://www.googleapis.com/auth/devstorage.full_control", true);
      googleStorageResourceObject0.getURL();
      assertTrue(googleStorageResourceObject0.isCreateBlobIfNotExists());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "c7MyM6:9M");
      googleStorageResourceObject0.getURI();
      assertTrue(googleStorageResourceObject0.isCreateBlobIfNotExists());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "http://metadata.google.internal", false);
      googleStorageResourceObject0.getURI();
      assertFalse(googleStorageResourceObject0.isCreateBlobIfNotExists());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      doReturn((Blob) null).when(storage0).get(any(com.google.cloud.storage.BlobId.class));
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "https://www.googleapis.com/auth/devstorage.full_control", true);
      googleStorageResourceObject0.getGoogleStorageObject();
      assertTrue(googleStorageResourceObject0.isCreateBlobIfNotExists());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Blob blob0 = mock(Blob.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(blob0).getName();
      doReturn((String) null, "").when(blob0).toString();
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      doReturn(blob0).when(storage0).get(any(com.google.cloud.storage.BlobId.class));
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "https://www.googleapis.com/auth/devstorage.full_control");
      googleStorageResourceObject0.getFilename();
      assertTrue(googleStorageResourceObject0.isCreateBlobIfNotExists());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Blob blob0 = mock(Blob.class, new ViolatedAssumptionAnswer());
      doReturn("").when(blob0).getName();
      doReturn("Invalid URI syntax", "").when(blob0).toString();
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      doReturn(blob0).when(storage0).get(any(com.google.cloud.storage.BlobId.class));
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "https://www.googleapis.com/auth/devstorage.full_control");
      String string0 = googleStorageResourceObject0.getFilename();
      assertTrue(googleStorageResourceObject0.isCreateBlobIfNotExists());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, (String) null);
      googleStorageResourceObject0.getDescription();
      assertTrue(googleStorageResourceObject0.isCreateBlobIfNotExists());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "}TWG}_G3L*8E&`A.");
      googleStorageResourceObject0.getDescription();
      assertTrue(googleStorageResourceObject0.isCreateBlobIfNotExists());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, (String) null, false);
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.lastModified();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "/");
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.lastModified();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "rGeAa0Z7 OC&", false);
      try { 
        googleStorageResourceObject0.lastModified();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Invalid URI syntax
         //
         verifyException("org.springframework.cloud.gcp.storage.GoogleStorageResourceObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      doReturn((Blob) null).when(storage0).get(any(com.google.cloud.storage.BlobId.class));
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "https://www.googleapis.com/auth/devstorage.full_control", true);
      try { 
        googleStorageResourceObject0.lastModified();
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // The blob was not found: https://www.googleapis.com/auth/devstorage.full_control
         //
         verifyException("org.springframework.cloud.gcp.storage.GoogleStorageResourceObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, (String) null);
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.getURL();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "Gfo?m<+_=R", false);
      try { 
        googleStorageResourceObject0.getURL();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Invalid URI syntax
         //
         verifyException("org.springframework.cloud.gcp.storage.GoogleStorageResourceObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, (String) null);
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.getURI();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "");
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.getOutputStream();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, (String) null);
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.getOutputStream();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "pGUxw-e43tyj.8c8v");
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.getOutputStream();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "<h\"n{R:v=5I");
      try { 
        googleStorageResourceObject0.getOutputStream();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Invalid URI syntax
         //
         verifyException("org.springframework.cloud.gcp.storage.GoogleStorageResourceObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "");
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.getInputStream();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Blob blob0 = mock(Blob.class, new ViolatedAssumptionAnswer());
      doReturn((ReadChannel) null).when(blob0).reader(any(com.google.cloud.storage.Blob.BlobSourceOption[].class));
      doReturn((String) null, (String) null).when(blob0).toString();
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      doReturn(blob0).when(storage0).get(any(com.google.cloud.storage.BlobId.class));
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "https://www.googleapis.com/auth/devstorage.full_control");
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.getInputStream();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // \"ch\" is null!
         //
         verifyException("java.nio.channels.Channels", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "',!,J");
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.getInputStream();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      doReturn((Blob) null).when(storage0).get(any(com.google.cloud.storage.BlobId.class));
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "https://www.googleapis.com/auth/devstorage.full_control");
      try { 
        googleStorageResourceObject0.getInputStream();
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // The blob was not found: https://www.googleapis.com/auth/devstorage.full_control
         //
         verifyException("org.springframework.cloud.gcp.storage.GoogleStorageResourceObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, (String) null);
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.getGoogleStorageObject();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "6");
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.getGoogleStorageObject();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "Invalid URI syntax");
      try { 
        googleStorageResourceObject0.getGoogleStorageObject();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Invalid URI syntax
         //
         verifyException("org.springframework.cloud.gcp.storage.GoogleStorageResourceObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "");
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.getFilename();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, (String) null, false);
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.getFilename();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "UJ");
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.getFilename();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, (String) null);
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.getBucket();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "3BF1", false);
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.getBucket();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "\noe", true);
      try { 
        googleStorageResourceObject0.getBucket();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Invalid URI syntax
         //
         verifyException("org.springframework.cloud.gcp.storage.GoogleStorageResourceObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "");
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.exists();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, (String) null);
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.exists();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "*Hj");
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.exists();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "", true);
      TimeUnit timeUnit0 = TimeUnit.MILLISECONDS;
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.createSignedUrl(timeUnit0, (-1798L));
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      TimeUnit timeUnit0 = TimeUnit.DAYS;
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, (String) null);
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.createSignedUrl(timeUnit0, 445L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "STANDARD", true);
      TimeUnit timeUnit0 = TimeUnit.MICROSECONDS;
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.createSignedUrl(timeUnit0, 1L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "ES;.[F%@:5pK|\u0005I");
      TimeUnit timeUnit0 = TimeUnit.MICROSECONDS;
      try { 
        googleStorageResourceObject0.createSignedUrl(timeUnit0, 676L);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Invalid URI syntax
         //
         verifyException("org.springframework.cloud.gcp.storage.GoogleStorageResourceObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, (String) null, false);
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.createRelative((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.springframework.cloud.gcp.storage.GoogleStorageResourceObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "", false);
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.contentLength();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, (String) null);
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.contentLength();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "org.springframework.cloud.gcp.storage.GoogleStorageResourceObject");
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.contentLength();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      doReturn((Blob) null).when(storage0).get(any(com.google.cloud.storage.BlobId.class));
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "https://www.googleapis.com/auth/devstorage.full_control", true);
      try { 
        googleStorageResourceObject0.contentLength();
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // The blob was not found: https://www.googleapis.com/auth/devstorage.full_control
         //
         verifyException("org.springframework.cloud.gcp.storage.GoogleStorageResourceObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      GoogleStorageResourceObject googleStorageResourceObject0 = null;
      try {
        googleStorageResourceObject0 = new GoogleStorageResourceObject((Storage) null, "f0W?xdW?1ZMUi&", false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Storage object can not be null
         //
         verifyException("org.springframework.util.Assert", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      GoogleStorageResourceObject googleStorageResourceObject0 = null;
      try {
        googleStorageResourceObject0 = new GoogleStorageResourceObject((Storage) null, "&S^G~%6Ep=@2dkU");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Storage object can not be null
         //
         verifyException("org.springframework.util.Assert", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "");
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.getGoogleStorageObject();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "");
      googleStorageResourceObject0.getURI();
      assertTrue(googleStorageResourceObject0.isCreateBlobIfNotExists());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "");
      googleStorageResourceObject0.getDescription();
      assertTrue(googleStorageResourceObject0.isCreateBlobIfNotExists());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Blob blob0 = mock(Blob.class, new ViolatedAssumptionAnswer());
      doReturn("$").when(blob0).getName();
      doReturn((String) null, "$").when(blob0).toString();
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      doReturn((Blob) null).when(storage0).create(any(com.google.cloud.storage.BlobInfo.class) , any(com.google.cloud.storage.Storage.BlobTargetOption[].class));
      doReturn((Bucket) null).when(storage0).create(any(com.google.cloud.storage.BucketInfo.class) , any(com.google.cloud.storage.Storage.BucketTargetOption[].class));
      doReturn(blob0, (Blob) null).when(storage0).get(any(com.google.cloud.storage.BlobId.class));
      doReturn((Bucket) null).when(storage0).get(anyString() , any(com.google.cloud.storage.Storage.BucketGetOption[].class));
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "https://www.googleapis.com/auth/devstorage.full_control");
      googleStorageResourceObject0.getFilename();
      try { 
        googleStorageResourceObject0.getOutputStream();
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // The blob was not found: https://www.googleapis.com/auth/devstorage.full_control
         //
         verifyException("org.springframework.cloud.gcp.storage.GoogleStorageResourceObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Blob blob0 = mock(Blob.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(blob0).exists(any(com.google.cloud.storage.Blob.BlobSourceOption[].class));
      doReturn((String) null).when(blob0).toString();
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      doReturn((Blob) null).when(storage0).create(any(com.google.cloud.storage.BlobInfo.class) , any(com.google.cloud.storage.Storage.BlobTargetOption[].class));
      doReturn((Bucket) null).when(storage0).create(any(com.google.cloud.storage.BucketInfo.class) , any(com.google.cloud.storage.Storage.BucketTargetOption[].class));
      doReturn(blob0).when(storage0).get(any(com.google.cloud.storage.BlobId.class));
      doReturn((Bucket) null).when(storage0).get(anyString() , any(com.google.cloud.storage.Storage.BucketGetOption[].class));
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "https://www.googleapis.com/auth/devstorage.full_control");
      try { 
        googleStorageResourceObject0.getOutputStream();
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // The blob was not found: https://www.googleapis.com/auth/devstorage.full_control
         //
         verifyException("org.springframework.cloud.gcp.storage.GoogleStorageResourceObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      doReturn((Blob) null).when(storage0).get(any(com.google.cloud.storage.BlobId.class));
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "https://www.googleapis.com/auth/devstorage.full_control", true);
      TimeUnit timeUnit0 = TimeUnit.NANOSECONDS;
      googleStorageResourceObject0.createSignedUrl(timeUnit0, 0L);
      assertTrue(googleStorageResourceObject0.isCreateBlobIfNotExists());
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      doReturn((Blob) null).when(storage0).get(any(com.google.cloud.storage.BlobId.class));
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "https://www.googleapis.com/auth/devstorage.full_control", true);
      boolean boolean0 = googleStorageResourceObject0.exists();
      assertTrue(googleStorageResourceObject0.isCreateBlobIfNotExists());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "C9]_sZWR!P*b~G}!");
      boolean boolean0 = googleStorageResourceObject0.isReadable();
      assertTrue(googleStorageResourceObject0.isCreateBlobIfNotExists());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, (String) null, false);
      boolean boolean0 = googleStorageResourceObject0.isCreateBlobIfNotExists();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "");
      boolean boolean0 = googleStorageResourceObject0.isWritable();
      assertTrue(googleStorageResourceObject0.isCreateBlobIfNotExists());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "C9]_sZWR!P*b~G}!");
      boolean boolean0 = googleStorageResourceObject0.isOpen();
      assertTrue(googleStorageResourceObject0.isCreateBlobIfNotExists());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "}oa`6y/ O@J7BioYX");
      try { 
        googleStorageResourceObject0.contentLength();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Invalid URI syntax
         //
         verifyException("org.springframework.cloud.gcp.storage.GoogleStorageResourceObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "https://www.googleapis.com/auth/devstorage.full_control", true);
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.getFile();
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // https://www.googleapis.com/auth/devstorage.full_control cannot be resolved to absolute file path
         //
         verifyException("org.springframework.cloud.gcp.storage.GoogleStorageResourceObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "");
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.getBucket();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "");
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.lastModified();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "C9]_sZWR!P*b~G}!");
      try { 
        googleStorageResourceObject0.getInputStream();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Invalid URI syntax
         //
         verifyException("org.springframework.cloud.gcp.storage.GoogleStorageResourceObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      Storage storage0 = mock(Storage.class, new ViolatedAssumptionAnswer());
      GoogleStorageResourceObject googleStorageResourceObject0 = new GoogleStorageResourceObject(storage0, "", true);
      // Undeclared exception!
      try { 
        googleStorageResourceObject0.getURL();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // URI is not absolute
         //
         verifyException("org.evosuite.runtime.mock.java.net.MockURI", e);
      }
  }
}
