language: java
dist: xenial
jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11

script:
  - mvn test jacoco:report

after_success:
  - mvn coveralls:report

dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.m2
