all-test:
  script:
      - set MAVEN_OPTS="-Xms6000m -Xmx8000m"
      - ./mvnw install --fail-at-end
      - cd test/docker-tests && ./mvnw install -Ddocker.url=tom.inf.unibz.it -DskipTests=false --fail-at-end
